default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: newlife4829
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: rails_test

test:
  <<: *default
  database: rails_test

production:
  <<: *default
  database: rails_test